# Generated by Django 4.2.10 on 2025-12-14 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assistencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Produto')),
                ('codigo', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Código/SKU')),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Barras')),
                ('categoria', models.CharField(choices=[('peca', 'Peça de Reposição'), ('acessorio', 'Acessório'), ('consumivel', 'Consumível'), ('liquido', 'Líquido/Concentrado'), ('filtro', 'Filtro')], max_length=20, verbose_name='Categoria')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('estoque_atual', models.IntegerField(default=0, verbose_name='Estoque Atual')),
                ('estoque_minimo', models.IntegerField(default=5, help_text='Alerta quando chegar a este nível', verbose_name='Estoque Mínimo')),
                ('estoque_maximo', models.IntegerField(blank=True, null=True, verbose_name='Estoque Máximo')),
                ('localizacao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Localização no Estoque')),
                ('preco_custo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço de Custo')),
                ('preco_venda', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço de Venda')),
                ('fornecedor', models.CharField(blank=True, max_length=150, null=True, verbose_name='Fornecedor')),
                ('unidade', models.CharField(default='UN', help_text='Ex: UN, CX, KG, L', max_length=10, verbose_name='Unidade')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='Imagem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('id_legado', models.IntegerField(blank=True, null=True, verbose_name='ID Sistema Legado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('ajuste', 'Ajuste')], max_length=10, verbose_name='Tipo')),
                ('motivo', models.CharField(choices=[('compra', 'Compra'), ('venda', 'Venda'), ('devolucao', 'Devolução'), ('manutencao', 'Manutenção/OS'), ('perda', 'Perda/Avaria'), ('inventario', 'Ajuste de Inventário'), ('transferencia', 'Transferência')], max_length=20, verbose_name='Motivo')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('estoque_anterior', models.IntegerField(verbose_name='Estoque Anterior')),
                ('estoque_posterior', models.IntegerField(verbose_name='Estoque Posterior')),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Unitário')),
                ('documento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Documento/NF')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ordem_servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assistencia.ordemservico', verbose_name='Ordem de Serviço')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='estoque.produto', verbose_name='Produto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.venda', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do Inventário')),
                ('status', models.CharField(choices=[('andamento', 'Em Andamento'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='andamento', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('total_itens', models.IntegerField(default=0, verbose_name='Total de Itens')),
                ('divergencias', models.IntegerField(default=0, verbose_name='Divergências Encontradas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Inventário',
                'verbose_name_plural': 'Inventários',
                'ordering': ['-data'],
            },
        ),
    ]
