# Generated by Django 4.2.10 on 2026-01-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='motivo',
            field=models.CharField(choices=[('compra', 'Compra'), ('venda', 'Venda'), ('devolucao', 'Devolução'), ('manutencao', 'Manutenção/OS'), ('uso_interno', 'Uso Interno'), ('perda', 'Perda/Avaria'), ('inventario', 'Ajuste de Inventário'), ('transferencia', 'Transferência')], max_length=20, verbose_name='Motivo'),
        ),
    ]
