# Generated by Django 4.2.10 on 2025-12-14 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Número de Série')),
                ('status', models.CharField(choices=[('estoque', 'Em Estoque'), ('vendido', 'Vendido'), ('alugado', 'Alugado'), ('manutencao', 'Em Manutenção'), ('demonstracao', 'Demonstração'), ('sucata', 'Sucata/Baixa')], db_index=True, default='estoque', max_length=20, verbose_name='Status')),
                ('data_aquisicao', models.DateField(blank=True, null=True, verbose_name='Data de Aquisição')),
                ('data_venda', models.DateField(blank=True, null=True, verbose_name='Data da Venda')),
                ('data_fim_garantia', models.DateField(blank=True, null=True, verbose_name='Fim da Garantia')),
                ('data_proxima_manutencao', models.DateField(blank=True, db_index=True, null=True, verbose_name='Próxima Manutenção')),
                ('data_ultima_manutencao', models.DateField(blank=True, null=True, verbose_name='Última Manutenção')),
                ('localizacao', models.CharField(blank=True, help_text='Onde o equipamento está fisicamente', max_length=100, null=True, verbose_name='Localização')),
                ('numero_power', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Power')),
                ('possui_power', models.BooleanField(default=False, verbose_name='Possui Power')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('condicao', models.CharField(default='novo', help_text='novo, semi-novo, usado, recondicionado', max_length=50, verbose_name='Condição')),
                ('id_legado', models.IntegerField(blank=True, null=True, verbose_name='ID Sistema Legado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos', to='clientes.cliente', verbose_name='Cliente/Proprietário')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModeloEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Modelo')),
                ('categoria', models.CharField(choices=[('aspirador', 'Aspirador Rainbow'), ('lavadora', 'Lavadora/Power'), ('acessorio', 'Acessório'), ('liquido', 'Líquido/Concentrado'), ('filtro', 'Filtro')], max_length=20, verbose_name='Categoria')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código do Modelo')),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda')),
                ('preco_aluguel_mensal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Aluguel/Mês')),
                ('preco_custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço de Custo')),
                ('voltagem', models.CharField(blank=True, help_text='Ex: 110V, 220V, Bivolt', max_length=20, null=True, verbose_name='Voltagem')),
                ('potencia', models.CharField(blank=True, max_length=20, null=True, verbose_name='Potência (W)')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso (kg)')),
                ('intervalo_manutencao_meses', models.IntegerField(default=12, help_text='Frequência recomendada para manutenção preventiva', verbose_name='Intervalo Manutenção (meses)')),
                ('garantia_meses', models.IntegerField(default=12, verbose_name='Garantia (meses)')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='equipamentos/modelos/', verbose_name='Imagem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modelo de Equipamento',
                'verbose_name_plural': 'Modelos de Equipamentos',
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preventiva', 'Preventiva'), ('corretiva', 'Corretiva'), ('limpeza', 'Limpeza'), ('revisao', 'Revisão Geral')], max_length=20, verbose_name='Tipo de Manutenção')),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='agendada', max_length=20, verbose_name='Status')),
                ('data_agendamento', models.DateField(verbose_name='Data Agendada')),
                ('data_realizacao', models.DateField(blank=True, null=True, verbose_name='Data de Realização')),
                ('descricao_problema', models.TextField(blank=True, null=True, verbose_name='Descrição do Problema')),
                ('servicos_realizados', models.TextField(blank=True, null=True, verbose_name='Serviços Realizados')),
                ('pecas_substituidas', models.TextField(blank=True, null=True, verbose_name='Peças Substituídas')),
                ('valor_mao_obra', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Mão de Obra')),
                ('valor_pecas', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Peças')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total')),
                ('coberto_garantia', models.BooleanField(default=False, verbose_name='Coberto pela Garantia')),
                ('garantia_servico_dias', models.IntegerField(default=90, verbose_name='Garantia do Serviço (dias)')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_manutencao', to='equipamentos.equipamento', verbose_name='Equipamento')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manutencoes_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsável')),
            ],
            options={
                'verbose_name': 'Histórico de Manutenção',
                'verbose_name_plural': 'Histórico de Manutenções',
                'ordering': ['-data_agendamento'],
            },
        ),
        migrations.AddField(
            model_name='equipamento',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos', to='equipamentos.modeloequipamento', verbose_name='Modelo'),
        ),
        migrations.AddIndex(
            model_name='equipamento',
            index=models.Index(fields=['numero_serie'], name='equipamento_numero__3a21af_idx'),
        ),
        migrations.AddIndex(
            model_name='equipamento',
            index=models.Index(fields=['status'], name='equipamento_status_353e18_idx'),
        ),
        migrations.AddIndex(
            model_name='equipamento',
            index=models.Index(fields=['cliente'], name='equipamento_cliente_8d4902_idx'),
        ),
        migrations.AddIndex(
            model_name='equipamento',
            index=models.Index(fields=['data_proxima_manutencao'], name='equipamento_data_pr_f2caa9_idx'),
        ),
    ]
