# Generated by Django 4.2.10 on 2025-12-14 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipamentos', '0001_initial'),
        ('agenda', '0001_initial'),
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendas', '0001_initial'),
        ('alugueis', '0001_initial'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, help_text='Número único do atendimento', max_length=20, null=True, unique=True)),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('em_andamento', 'Em Andamento'), ('pausado', 'Pausado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='agendado', max_length=20)),
                ('data_agendada', models.DateField(blank=True, null=True)),
                ('hora_agendada', models.TimeField(blank=True, null=True)),
                ('data_inicio', models.DateTimeField(blank=True, help_text='Quando o atendimento foi iniciado', null=True)),
                ('data_fim', models.DateTimeField(blank=True, help_text='Quando o atendimento foi finalizado', null=True)),
                ('checkin_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('checkin_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('checkin_endereco', models.CharField(blank=True, help_text='Endereço obtido via GPS', max_length=500)),
                ('checkin_timestamp', models.DateTimeField(blank=True, null=True)),
                ('checkout_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('checkout_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('checkout_timestamp', models.DateTimeField(blank=True, null=True)),
                ('relatorio', models.TextField(blank=True, help_text='Relatório geral do atendimento')),
                ('observacoes_internas', models.TextField(blank=True, help_text='Observações internas (não visíveis ao cliente)')),
                ('satisfacao_nota', models.PositiveSmallIntegerField(blank=True, help_text='Nota de satisfação (1-5)', null=True)),
                ('satisfacao_comentario', models.TextField(blank=True, help_text='Comentário do cliente sobre satisfação')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, help_text='Valor total do atendimento', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agendamento', models.ForeignKey(blank=True, help_text='Agendamento que originou este atendimento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='agenda.agendamento')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='clientes.cliente')),
                ('consultor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to=settings.AUTH_USER_MODEL)),
                ('conta_receber', models.ForeignKey(blank=True, help_text='Conta a receber gerada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='financeiro.contareceber')),
                ('contrato_aluguel', models.ForeignKey(blank=True, help_text='Contrato de aluguel relacionado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='alugueis.contratoaluguel')),
                ('endereco', models.ForeignKey(blank=True, help_text='Endereço do atendimento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='clientes.endereco')),
                ('equipamento', models.ForeignKey(blank=True, help_text='Equipamento Rainbow envolvido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='equipamentos.equipamento')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
                'ordering': ['-data_agendada', '-hora_agendada'],
            },
        ),
        migrations.CreateModel(
            name='CampoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do campo', max_length=100)),
                ('codigo', models.CharField(help_text='Código único do campo (ex: foto_ficha)', max_length=50)),
                ('tipo_campo', models.CharField(choices=[('texto', 'Texto Curto'), ('textarea', 'Texto Longo'), ('numero', 'Número'), ('decimal', 'Decimal/Valor'), ('data', 'Data'), ('hora', 'Hora'), ('datetime', 'Data e Hora'), ('boolean', 'Sim/Não'), ('select', 'Seleção Única'), ('multiselect', 'Seleção Múltipla'), ('foto', 'Foto'), ('assinatura', 'Assinatura'), ('gps', 'Localização GPS')], default='texto', max_length=20)),
                ('descricao', models.TextField(blank=True, help_text='Instruções para o consultor')),
                ('placeholder', models.CharField(blank=True, help_text='Texto de exemplo no campo', max_length=200)),
                ('opcoes', models.JSONField(blank=True, default=list, help_text='Opções para campos select/multiselect (lista JSON)')),
                ('valor_padrao', models.CharField(blank=True, help_text='Valor padrão do campo', max_length=200)),
                ('obrigatorio', models.BooleanField(default=False, help_text='Campo obrigatório?')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição no formulário')),
                ('secao', models.CharField(blank=True, help_text='Agrupa campos em seções (ex: Fotos, Pagamento)', max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campo de Serviço',
                'verbose_name_plural': 'Campos de Serviço',
                'ordering': ['tipo_servico', 'ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do tipo de serviço', max_length=100)),
                ('codigo', models.CharField(help_text='Código único (ex: pos_venda, retorno_pos_venda)', max_length=50, unique=True)),
                ('categoria', models.CharField(blank=True, choices=[('pos_venda', 'Pós-Venda'), ('aluguel', 'Aluguel'), ('visita', 'Visita'), ('manutencao', 'Manutenção'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do serviço')),
                ('cor', models.CharField(blank=True, default='#3498db', help_text='Cor para identificação visual (hex)', max_length=7)),
                ('icone', models.CharField(blank=True, help_text='Nome do ícone (Material Icons)', max_length=50)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Serviço',
                'verbose_name_plural': 'Tipos de Serviço',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='FotoAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ficha', 'Ficha/Formulário'), ('equipamento', 'Equipamento'), ('contrato', 'Contrato'), ('ambiente', 'Ambiente'), ('problema', 'Problema Identificado'), ('antes', 'Antes do Serviço'), ('depois', 'Depois do Serviço'), ('assinatura', 'Assinatura Cliente'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('foto', models.ImageField(upload_to='atendimentos/fotos/%Y/%m/')),
                ('descricao', models.CharField(blank=True, help_text='Descrição da foto', max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Momento em que a foto foi tirada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='atendimentos.atendimento')),
                ('campo', models.ForeignKey(blank=True, help_text='Campo do formulário que solicitou esta foto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos', to='atendimentos.camposervico')),
            ],
            options={
                'verbose_name': 'Foto de Atendimento',
                'verbose_name_plural': 'Fotos de Atendimento',
                'ordering': ['atendimento', 'tipo', 'timestamp'],
            },
        ),
        migrations.AddField(
            model_name='camposervico',
            name='tipo_servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='atendimentos.tiposervico'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='tipo_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='atendimentos.tiposervico'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='venda',
            field=models.ForeignKey(blank=True, help_text='Venda relacionada (pós-venda)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='vendas.venda'),
        ),
        migrations.CreateModel(
            name='RespostaAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_texto', models.TextField(blank=True, help_text='Valor para campos texto')),
                ('valor_numero', models.DecimalField(blank=True, decimal_places=4, help_text='Valor para campos numéricos', max_digits=15, null=True)),
                ('valor_boolean', models.BooleanField(blank=True, help_text='Valor para campos sim/não', null=True)),
                ('valor_data', models.DateField(blank=True, help_text='Valor para campos data', null=True)),
                ('valor_hora', models.TimeField(blank=True, help_text='Valor para campos hora', null=True)),
                ('valor_datetime', models.DateTimeField(blank=True, help_text='Valor para campos data/hora', null=True)),
                ('valor_json', models.JSONField(blank=True, default=dict, help_text='Valor para campos complexos (select múltiplo, GPS, etc)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='atendimentos.atendimento')),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='atendimentos.camposervico')),
            ],
            options={
                'verbose_name': 'Resposta de Atendimento',
                'verbose_name_plural': 'Respostas de Atendimento',
                'unique_together': {('atendimento', 'campo')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='camposervico',
            unique_together={('tipo_servico', 'codigo')},
        ),
    ]
