# Generated by Django 4.2.10 on 2025-12-14 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipamentos', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoAluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Número do Contrato')),
                ('data_inicio', models.DateField(db_index=True, verbose_name='Data de Início')),
                ('data_fim_prevista', models.DateField(help_text='Data prevista para encerramento/renovação', verbose_name='Data Fim Prevista')),
                ('data_fim_real', models.DateField(blank=True, null=True, verbose_name='Data Fim Real')),
                ('duracao_meses', models.IntegerField(default=12, verbose_name='Duração (meses)')),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Mensal')),
                ('valor_caucao', models.DecimalField(decimal_places=2, default=0, help_text='Valor depositado como garantia', max_digits=10, verbose_name='Valor Caução')),
                ('dia_vencimento', models.IntegerField(default=10, help_text='Dia do mês para vencimento das parcelas', verbose_name='Dia Vencimento')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('encerrado', 'Encerrado'), ('suspenso', 'Suspenso'), ('convertido', 'Convertido em Venda'), ('cancelado', 'Cancelado')], db_index=True, default='ativo', max_length=20, verbose_name='Status')),
                ('tipo_periodicidade', models.CharField(choices=[('mensal', 'Mensal'), ('semanal', 'Semanal'), ('diario', 'Diário')], default='mensal', max_length=20, verbose_name='Periodicidade')),
                ('valor_residual', models.DecimalField(blank=True, decimal_places=2, help_text='Valor para compra do equipamento', max_digits=10, null=True, verbose_name='Valor Residual')),
                ('data_entrega', models.DateField(blank=True, null=True, verbose_name='Data da Entrega')),
                ('entregue', models.BooleanField(default=False, verbose_name='Entregue')),
                ('data_devolucao', models.DateField(blank=True, null=True, verbose_name='Data da Devolução')),
                ('devolvido', models.BooleanField(default=False, verbose_name='Devolvido')),
                ('termos_aceitos', models.BooleanField(default=False, verbose_name='Termos Aceitos')),
                ('documento_contrato', models.FileField(blank=True, null=True, upload_to='contratos/alugueis/', verbose_name='Documento do Contrato')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('id_legado', models.IntegerField(blank=True, null=True, verbose_name='ID Sistema Legado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_aluguel', to='clientes.cliente', verbose_name='Cliente/Locatário')),
                ('consultor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_aluguel', to=settings.AUTH_USER_MODEL, verbose_name='Consultor')),
                ('endereco_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.endereco', verbose_name='Endereço de Entrega')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_aluguel', to='equipamentos.equipamento', verbose_name='Equipamento')),
                ('venda_conversao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_convertidos', to='vendas.venda', verbose_name='Venda (se convertido)')),
            ],
            options={
                'verbose_name': 'Contrato de Aluguel',
                'verbose_name_plural': 'Contratos de Aluguel',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ParcelaAluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Nº Parcela')),
                ('mes_referencia', models.CharField(help_text='Formato: MM/YYYY', max_length=7, verbose_name='Mês Referência')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data_vencimento', models.DateField(db_index=True, verbose_name='Data Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data Pagamento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga'), ('atrasada', 'Atrasada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status')),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Pago')),
                ('forma_pagamento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Forma de Pagamento')),
                ('juros', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Juros')),
                ('multa', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Multa')),
                ('codigo_pix', models.TextField(blank=True, null=True, verbose_name='Código PIX')),
                ('linha_digitavel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Linha Digitável')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='alugueis.contratoaluguel', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Parcela de Aluguel',
                'verbose_name_plural': 'Parcelas de Aluguel',
                'ordering': ['contrato', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoAluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('criacao', 'Criação do Contrato'), ('entrega', 'Entrega do Equipamento'), ('pagamento', 'Pagamento Recebido'), ('atraso', 'Atraso Detectado'), ('cobranca', 'Cobrança Enviada'), ('renovacao', 'Renovação'), ('suspensao', 'Suspensão'), ('reativacao', 'Reativação'), ('devolucao', 'Devolução do Equipamento'), ('conversao', 'Conversão em Venda'), ('encerramento', 'Encerramento')], max_length=20, verbose_name='Evento')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('automatico', models.BooleanField(default=False, help_text='Gerado automaticamente pelo sistema/IA', verbose_name='Evento Automático')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='alugueis.contratoaluguel', verbose_name='Contrato')),
                ('parcela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alugueis.parcelaaluguel', verbose_name='Parcela Relacionada')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico de Aluguel',
                'verbose_name_plural': 'Históricos de Aluguel',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='parcelaaluguel',
            index=models.Index(fields=['data_vencimento', 'status'], name='alugueis_pa_data_ve_3e34c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='parcelaaluguel',
            unique_together={('contrato', 'numero')},
        ),
    ]
