# Generated by Django 4.2.10 on 2025-12-14 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipamentos', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Número OS')),
                ('descricao_problema', models.TextField(verbose_name='Descrição do Problema')),
                ('diagnostico', models.TextField(blank=True, null=True, verbose_name='Diagnóstico Técnico')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('analise', 'Em Análise'), ('orcamento', 'Orçamento Enviado'), ('aprovado', 'Aprovado'), ('execucao', 'Em Execução'), ('finalizada', 'Finalizada'), ('entregue', 'Entregue'), ('cancelada', 'Cancelada')], db_index=True, default='aberta', max_length=20, verbose_name='Status')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10, verbose_name='Prioridade')),
                ('em_garantia', models.BooleanField(default=False, verbose_name='Em Garantia')),
                ('data_abertura', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Abertura')),
                ('data_previsao', models.DateField(blank=True, null=True, verbose_name='Previsão de Conclusão')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('data_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Data de Entrega')),
                ('valor_mao_obra', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Mão de Obra')),
                ('valor_pecas', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Peças')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total')),
                ('pago', models.BooleanField(default=False, verbose_name='Pago')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('forma_pagamento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Forma de Pagamento')),
                ('servicos_realizados', models.TextField(blank=True, null=True, verbose_name='Serviços Realizados')),
                ('garantia_servico_dias', models.IntegerField(default=90, verbose_name='Garantia do Serviço (dias)')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atendente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico_atendente', to=settings.AUTH_USER_MODEL, verbose_name='Atendente')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='clientes.cliente', verbose_name='Cliente')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='equipamentos.equipamento', verbose_name='Equipamento')),
                ('tecnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico_tecnico', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsável')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['-data_abertura'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('quantidade', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='assistencia.ordemservico', verbose_name='Ordem de Serviço')),
            ],
            options={
                'verbose_name': 'Item da OS',
                'verbose_name_plural': 'Itens da OS',
            },
        ),
    ]
