# Generated by Django 4.2.10 on 2025-12-14 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
        ('assistencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemordemservico',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.produto', verbose_name='Produto'),
        ),
    ]
