# Generated by Django 4.2.10 on 2025-12-14 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0001_initial'),
        ('assistencia', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTarefaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('categoria', models.CharField(choices=[('orcamento', '💰 Orçamento'), ('conserto', '🔧 Conserto'), ('limpeza', '🧼 Limpeza'), ('montagem', '🔩 Montagem'), ('organizacao', '🧹 Organização'), ('outros', '📋 Outros')], max_length=20, verbose_name='Categoria')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('tempo_estimado_minutos', models.IntegerField(default=30, help_text='Tempo médio para realizar esta tarefa', verbose_name='Tempo Estimado (min)')),
                ('requer_equipamento', models.BooleanField(default=False, help_text='Tarefa precisa estar vinculada a um equipamento', verbose_name='Requer Equipamento?')),
                ('requer_os', models.BooleanField(default=False, help_text='Tarefa precisa estar vinculada a uma Ordem de Serviço', verbose_name='Requer OS?')),
                ('pode_ser_recorrente', models.BooleanField(default=False, help_text='Tarefa pode ser agendada para repetir automaticamente', verbose_name='Pode ser Recorrente?')),
                ('icone', models.CharField(default='📋', max_length=10, verbose_name='Ícone')),
                ('cor', models.CharField(default='#3498db', help_text='Ex: #3498db', max_length=7, verbose_name='Cor (hex)')),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tipo de Tarefa Técnica',
                'verbose_name_plural': 'Tipos de Tarefas Técnicas',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='TarefaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título/Descrição')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_agendada', models.DateField(blank=True, db_index=True, null=True, verbose_name='Data Agendada')),
                ('prioridade', models.IntegerField(choices=[(1, '🟢 Baixa'), (2, '🟡 Normal'), (3, '🟠 Alta'), (4, '🔴 Urgente')], db_index=True, default=2, verbose_name='Prioridade')),
                ('posicao_fila', models.IntegerField(default=0, help_text='Ordem de execução na fila do dia', verbose_name='Posição na Fila')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('fila', 'Na Fila'), ('andamento', 'Em Andamento'), ('pausada', 'Pausada'), ('aguardando', 'Aguardando'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], db_index=True, default='pendente', max_length=20, verbose_name='Status')),
                ('motivo_aguardando', models.CharField(blank=True, help_text='Ex: Aguardando peças, Aguardando aprovação cliente', max_length=200, verbose_name='Motivo de Aguardar')),
                ('tempo_estimado_minutos', models.IntegerField(default=30, verbose_name='Tempo Estimado (min)')),
                ('data_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Início da Execução')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Conclusão')),
                ('tempo_gasto_minutos', models.IntegerField(default=0, help_text='Tempo total trabalhado na tarefa', verbose_name='Tempo Gasto (min)')),
                ('resultado', models.TextField(blank=True, verbose_name='Resultado/Observações Finais')),
                ('recorrente', models.BooleanField(default=False, verbose_name='Tarefa Recorrente?')),
                ('frequencia_recorrencia', models.CharField(blank=True, choices=[('diaria', 'Diária'), ('semanal', 'Semanal'), ('quinzenal', 'Quinzenal'), ('mensal', 'Mensal')], max_length=20, verbose_name='Frequência')),
                ('dias_semana', models.CharField(blank=True, help_text='Ex: seg,ter,qua,qui,sex', max_length=20, verbose_name='Dias da Semana')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_tecnicas', to='clientes.cliente', verbose_name='Cliente')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_tecnicas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('equipamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_tecnicas', to='equipamentos.equipamento', verbose_name='Equipamento')),
                ('ordem_servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='assistencia.ordemservico', verbose_name='Ordem de Serviço')),
                ('tecnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_tecnicas', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsável')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarefas', to='assistencia.tipotarefatecnica', verbose_name='Tipo de Tarefa')),
            ],
            options={
                'verbose_name': 'Tarefa Técnica',
                'verbose_name_plural': 'Tarefas Técnicas',
                'ordering': ['-prioridade', 'posicao_fila', 'data_agendada', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistroTempoTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(verbose_name='Início')),
                ('fim', models.DateTimeField(blank=True, null=True, verbose_name='Fim')),
                ('duracao_minutos', models.IntegerField(default=0, verbose_name='Duração (min)')),
                ('observacao', models.CharField(blank=True, max_length=200, verbose_name='Observação')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_tempo', to='assistencia.tarefatecnica', verbose_name='Tarefa')),
                ('tecnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Técnico')),
            ],
            options={
                'verbose_name': 'Registro de Tempo',
                'verbose_name_plural': 'Registros de Tempo',
                'ordering': ['-inicio'],
            },
        ),
    ]
