# Generated by Django 4.2.10 on 2026-01-11 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
        ('assistencia', '0003_tarefas_tecnicas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemordemservico',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_os', to='estoque.produto', verbose_name='Produto'),
        ),
    ]
