# Generated by Django 4.2.10 on 2025-12-14 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipamentos', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Número da Venda')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcialmente Paga'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], db_index=True, default='pendente', max_length=20, verbose_name='Status')),
                ('data_venda', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Data da Venda')),
                ('data_entrega', models.DateField(blank=True, null=True, verbose_name='Data de Entrega')),
                ('entregue', models.BooleanField(default=False, verbose_name='Entregue')),
                ('tipo_entrega', models.CharField(choices=[('retirada', 'Retirada no Local'), ('domicilio', 'Entrega em Domicílio'), ('correios', 'Correios'), ('transportadora', 'Transportadora')], default='domicilio', max_length=20, verbose_name='Tipo de Entrega')),
                ('valor_produtos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor dos Produtos')),
                ('valor_custo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor de Custo')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Desconto')),
                ('acrescimo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Acréscimo')),
                ('valor_frete', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do Frete')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Total')),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('credito', 'Cartão de Crédito'), ('debito', 'Cartão de Débito'), ('boleto', 'Boleto'), ('transferencia', 'Transferência'), ('cheque', 'Cheque'), ('financiamento', 'Financiamento')], default='pix', max_length=20, verbose_name='Forma de Pagamento')),
                ('numero_parcelas', models.IntegerField(default=1, verbose_name='Número de Parcelas')),
                ('data_primeiro_vencimento', models.DateField(blank=True, null=True, verbose_name='Data 1º Vencimento')),
                ('pontos', models.DecimalField(decimal_places=2, default=0, help_text='Pontos para comissão do vendedor', max_digits=10, verbose_name='Pontos')),
                ('comissao', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Comissão')),
                ('nota_fiscal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número NF')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('lancamento', models.CharField(blank=True, help_text='Origem da venda (ex: Demonstração, Indicação)', max_length=50, null=True, verbose_name='Lançamento/Campanha')),
                ('id_legado', models.IntegerField(blank=True, null=True, verbose_name='ID Sistema Legado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='clientes.cliente', verbose_name='Cliente')),
                ('vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor/Consultor')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-data_venda', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Nº Parcela')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data_vencimento', models.DateField(db_index=True, verbose_name='Data Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data Pagamento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga'), ('atrasada', 'Atrasada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status')),
                ('forma_pagamento', models.CharField(blank=True, max_length=20, null=True, verbose_name='Forma de Pagamento Utilizada')),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Pago')),
                ('juros', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Juros')),
                ('multa', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Multa')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='vendas.venda', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'ordering': ['venda', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário')),
                ('valor_custo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo Unitário')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Total')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_venda', to='equipamentos.equipamento', verbose_name='Equipamento (c/ série)')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_venda', to='equipamentos.modeloequipamento', verbose_name='Modelo')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendas.venda', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Item da Venda',
                'verbose_name_plural': 'Itens da Venda',
            },
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['numero'], name='vendas_vend_numero_03706f_idx'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['cliente'], name='vendas_vend_cliente_0d3155_idx'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['status'], name='vendas_vend_status_be1af5_idx'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['data_venda'], name='vendas_vend_data_ve_933af3_idx'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['vendedor'], name='vendas_vend_vendedo_089760_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='parcela',
            unique_together={('venda', 'numero')},
        ),
    ]
