# Generated by Django 4.2.10 on 2026-01-11 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
        ('estoque', '0001_initial'),
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='produto',
            field=models.ForeignKey(blank=True, help_text='Para peças/acessórios do estoque (baixa automática)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_venda', to='estoque.produto', verbose_name='Produto do Estoque'),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_venda', to='equipamentos.modeloequipamento', verbose_name='Modelo'),
        ),
    ]
