# Generated by Django 4.2.10 on 2025-12-14 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alugueis', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True, verbose_name='Data')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado')], default='aberto', max_length=10, verbose_name='Status')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo Inicial')),
                ('total_entradas', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Entradas')),
                ('total_saidas', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Saídas')),
                ('saldo_final', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo Final')),
                ('data_hora_abertura', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora Abertura')),
                ('data_hora_fechamento', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Fechamento')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('usuario_abertura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caixas_abertos', to=settings.AUTH_USER_MODEL, verbose_name='Aberto por')),
                ('usuario_fechamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caixas_fechados', to=settings.AUTH_USER_MODEL, verbose_name='Fechado por')),
            ],
            options={
                'verbose_name': 'Caixa',
                'verbose_name_plural': 'Caixas',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('fornecedor', models.CharField(blank=True, max_length=150, null=True, verbose_name='Fornecedor')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Pago')),
                ('juros', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Juros')),
                ('multa', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Multa')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto')),
                ('data_emissao', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Emissão')),
                ('data_vencimento', models.DateField(db_index=True, verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga'), ('atrasada', 'Atrasada'), ('cancelada', 'Cancelada')], db_index=True, default='pendente', max_length=20, verbose_name='Status')),
                ('forma_pagamento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Forma de Pagamento')),
                ('documento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Documento/NF')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('id_legado', models.IntegerField(blank=True, null=True, verbose_name='ID Sistema Legado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conta a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
                'ordering': ['data_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Pago')),
                ('juros', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Juros')),
                ('multa', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Multa')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto')),
                ('data_emissao', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Emissão')),
                ('data_vencimento', models.DateField(db_index=True, verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga'), ('atrasada', 'Atrasada'), ('cancelada', 'Cancelada')], db_index=True, default='pendente', max_length=20, verbose_name='Status')),
                ('forma_pagamento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Forma de Pagamento')),
                ('documento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Documento/Referência')),
                ('pontos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pontos')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('id_legado', models.IntegerField(blank=True, null=True, verbose_name='ID Sistema Legado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_receber', to='clientes.cliente', verbose_name='Cliente')),
                ('consultor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_receber', to=settings.AUTH_USER_MODEL, verbose_name='Consultor')),
                ('contrato_aluguel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_receber', to='alugueis.contratoaluguel', verbose_name='Contrato de Aluguel')),
            ],
            options={
                'verbose_name': 'Conta a Receber',
                'verbose_name_plural': 'Contas a Receber',
                'ordering': ['data_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='PlanoConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Conta')),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10, verbose_name='Tipo')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True)),
                ('conta_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcontas', to='financeiro.planoconta', verbose_name='Conta Pai')),
            ],
            options={
                'verbose_name': 'Plano de Conta',
                'verbose_name_plural': 'Plano de Contas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10, verbose_name='Tipo')),
                ('movimento', models.CharField(choices=[('venda', 'Venda'), ('aluguel', 'Aluguel'), ('servico', 'Serviço'), ('despesa', 'Despesa'), ('transferencia', 'Transferência'), ('ajuste', 'Ajuste')], max_length=20, verbose_name='Movimento')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('data', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Data')),
                ('forma_pagamento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Forma de Pagamento')),
                ('documento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Documento')),
                ('pontos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pontos')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('id_legado', models.IntegerField(blank=True, null=True, verbose_name='ID Sistema Legado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caixa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='financeiro.caixa', verbose_name='Caixa')),
                ('consultor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_consultor', to=settings.AUTH_USER_MODEL, verbose_name='Consultor')),
                ('conta_pagar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='financeiro.contapagar', verbose_name='Conta a Pagar')),
                ('conta_receber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='financeiro.contareceber', verbose_name='Conta a Receber')),
                ('plano_conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.planoconta', verbose_name='Plano de Conta')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='vendas.venda', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-data', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contareceber',
            name='plano_conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.planoconta', verbose_name='Plano de Conta'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_receber', to='vendas.venda', verbose_name='Venda'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='plano_conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.planoconta', verbose_name='Plano de Conta'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['data_vencimento', 'status'], name='financeiro__data_ve_cf81e6_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['cliente'], name='financeiro__cliente_3de520_idx'),
        ),
    ]
