# Generated by Django 4.2.10 on 2026-01-11 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistencia', '0004_alter_itemordemservico_produto'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contareceber',
            name='ordem_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_receber', to='assistencia.ordemservico', verbose_name='Ordem de Servico'),
        ),
    ]
