# Generated by Django 4.2.10 on 2025-12-14 11:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=150, verbose_name='Nome Completo')),
                ('tipo_pessoa', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2, verbose_name='Tipo de Pessoa')),
                ('cpf_cnpj', models.CharField(blank=True, help_text='Formato: 000.000.000-00 ou 00.000.000/0000-00', max_length=18, null=True, unique=True, verbose_name='CPF/CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual')),
                ('telefone', models.CharField(db_index=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Número de telefone deve conter 10-15 dígitos.', regex='^\\+?1?\\d{10,15}$')], verbose_name='Telefone Principal')),
                ('telefone_secundario', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Secundário')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('whatsapp', models.CharField(blank=True, help_text='Número para comunicação via WhatsApp Business', max_length=20, null=True, verbose_name='WhatsApp')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('prospecto', 'Prospecto')], db_index=True, default='ativo', max_length=20, verbose_name='Status')),
                ('perfil', models.CharField(choices=[('diamante', 'Diamante'), ('ouro', 'Ouro'), ('prata', 'Prata'), ('bronze', 'Bronze'), ('standard', 'Standard')], default='standard', max_length=20, verbose_name='Perfil/Categoria')),
                ('segmento', models.CharField(choices=[('residencial', 'Residencial'), ('comercial', 'Comercial'), ('industrial', 'Industrial')], default='residencial', max_length=20, verbose_name='Segmento')),
                ('poder_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Poder de Compra Estimado')),
                ('possui_rainbow', models.BooleanField(default=False, verbose_name='Possui Rainbow')),
                ('data_compra_rainbow', models.DateField(blank=True, null=True, verbose_name='Data da Compra Rainbow')),
                ('data_proxima_ligacao', models.DateField(blank=True, db_index=True, null=True, verbose_name='Data Próxima Ligação')),
                ('data_ultimo_contato', models.DateTimeField(blank=True, null=True, verbose_name='Último Contato')),
                ('status_acompanhamento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status do Acompanhamento')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('relatorio', models.TextField(blank=True, null=True, verbose_name='Relatório de Atendimento')),
                ('banco', models.CharField(blank=True, max_length=50, null=True, verbose_name='Banco')),
                ('agencia', models.CharField(blank=True, max_length=10, null=True, verbose_name='Agência')),
                ('conta', models.CharField(blank=True, max_length=20, null=True, verbose_name='Conta')),
                ('origem', models.CharField(blank=True, help_text='Como o cliente chegou até nós', max_length=50, null=True, verbose_name='Origem do Lead')),
                ('perfil_marketing', models.CharField(blank=True, max_length=100, null=True, verbose_name='Perfil de Marketing')),
                ('aceita_whatsapp', models.BooleanField(default=True, verbose_name='Aceita WhatsApp Marketing')),
                ('aceita_email', models.BooleanField(default=True, verbose_name='Aceita E-mail Marketing')),
                ('id_legado', models.IntegerField(blank=True, help_text='ID do cliente no sistema PHP antigo', null=True, verbose_name='ID Sistema Legado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('consultor_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to=settings.AUTH_USER_MODEL, verbose_name='Consultor Responsável')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoInteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ligacao', 'Ligação Telefônica'), ('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('visita', 'Visita'), ('reuniao', 'Reunião'), ('demonstracao', 'Demonstração')], max_length=20, verbose_name='Tipo de Interação')),
                ('direcao', models.CharField(choices=[('entrada', 'Recebida'), ('saida', 'Realizada')], default='saida', max_length=10, verbose_name='Direção')),
                ('descricao', models.TextField(verbose_name='Descrição/Resumo')),
                ('resultado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Resultado')),
                ('proxima_acao', models.TextField(blank=True, null=True, verbose_name='Próxima Ação')),
                ('data_proxima_acao', models.DateField(blank=True, null=True, verbose_name='Data Próxima Ação')),
                ('gerado_por_ia', models.BooleanField(default=False, verbose_name='Gerado por IA')),
                ('whatsapp_message_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Mensagem WhatsApp')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_interacoes', to='clientes.cliente', verbose_name='Cliente')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Histórico de Interação',
                'verbose_name_plural': 'Histórico de Interações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('residencial', 'Residencial'), ('comercial', 'Comercial'), ('entrega', 'Entrega'), ('cobranca', 'Cobrança')], default='residencial', max_length=20, verbose_name='Tipo de Endereço')),
                ('principal', models.BooleanField(default=False, verbose_name='Endereço Principal')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(db_index=True, max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('pais', models.CharField(default='Brasil', max_length=50, verbose_name='País')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'ordering': ['-principal', 'tipo'],
            },
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['telefone'], name='clientes_cl_telefon_08ef14_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['cpf_cnpj'], name='clientes_cl_cpf_cnp_0eeb49_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['status', 'perfil'], name='clientes_cl_status_8aa059_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['consultor_responsavel', 'data_proxima_ligacao'], name='clientes_cl_consult_0defea_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['created_at'], name='clientes_cl_created_cc2563_idx'),
        ),
    ]
