# Generated by Django 4.2.10 on 2026-01-09 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Número de telefone deve conter 10-15 dígitos.', regex='^\\+?1?\\d{10,15}$')], verbose_name='Telefone Principal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='whatsapp',
            field=models.CharField(blank=True, db_index=True, help_text='Número único para comunicação via WhatsApp Business', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Número de telefone deve conter 10-15 dígitos.', regex='^\\+?1?\\d{10,15}$')], verbose_name='WhatsApp'),
        ),
    ]
