# Generated by Django 4.2.10 on 2026-01-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_whatsapp_unique_telefone_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='poder_compra',
        ),
        migrations.AddField(
            model_name='cliente',
            name='giro',
            field=models.CharField(blank=True, choices=[('12_meses', '12 meses'), ('15_meses', '15 meses'), ('18_meses', '18 meses'), ('24_meses', '24 meses')], max_length=20, null=True, verbose_name='Giro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='poder_aquisitivo',
            field=models.CharField(blank=True, choices=[('a', 'A'), ('b_mais', 'B+'), ('b', 'B')], max_length=20, null=True, verbose_name='Poder Aquisitivo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='perfil',
            field=models.CharField(choices=[('lho', 'LHO'), ('ema', 'EMA')], default='lho', max_length=20, verbose_name='Segmentação'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='segmento',
            field=models.CharField(choices=[('residencial', 'Residencial'), ('comercial', 'Comercial')], default='residencial', max_length=20, verbose_name='Segmento'),
        ),
    ]
