# Generated by Django 4.2.10 on 2026-01-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_add_poder_aquisitivo_giro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='liquido',
            field=models.CharField(blank=True, choices=[('nenhum', 'Nenhum'), ('essencias', 'Essências'), ('air_fresh', 'Air Fresh'), ('shampoo', 'Shampoo'), ('kit', 'Kit'), ('kit_air_fresh', 'Kit / Air Fresh'), ('todos', 'Todos')], max_length=20, null=True, verbose_name='Líquido'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='perfil_mkt',
            field=models.CharField(blank=True, choices=[('limpeza', 'Limpeza'), ('alergia', 'Alergia'), ('animais', 'Animais'), ('outro', 'Outro')], max_length=20, null=True, verbose_name='Perfil de MKT'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='produto',
            field=models.CharField(blank=True, choices=[('pos_venda', 'Pós-venda'), ('plano_mensal', 'Plano Mensal'), ('plano_bimestral', 'Plano Bimestral'), ('plano_trimestral', 'Plano Trimestral'), ('avulso', 'Avulso'), ('outro', 'Outro')], max_length=20, null=True, verbose_name='Produto'),
        ),
    ]
