# Generated by Django 4.2.10 on 2026-01-09 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0004_add_produto_liquido_perfil_mkt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='giro',
            field=models.CharField(blank=True, choices=[('12_meses', '12 meses'), ('15_meses', '15 meses'), ('18_meses', '18 meses'), ('24_meses', '24 meses')], max_length=20, null=True, verbose_name='Giro da Preventiva'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='liquido',
            field=models.CharField(blank=True, choices=[('nenhum', 'Nenhum'), ('kit_essencias', 'Kit Essências'), ('air_fresh', 'Air Fresh'), ('shampoo', 'Shampoo'), ('kit_air_fresh', 'Kit / Air Fresh'), ('todos', 'Todos')], max_length=20, null=True, verbose_name='Líquido'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='perfil',
            field=models.CharField(choices=[('lho', 'LHO'), ('ema', 'EMA'), ('bronze', 'Bronze'), ('prata', 'Prata'), ('ouro', 'Ouro'), ('diamante', 'Diamante')], default='lho', max_length=20, verbose_name='Segmentação'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='poder_aquisitivo',
            field=models.CharField(blank=True, choices=[('a', 'A'), ('b_mais', 'B+'), ('b', 'B')], max_length=20, null=True, verbose_name='Aquisitivo'),
        ),
        migrations.CreateModel(
            name='ClienteFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='clientes/fotos/%Y/%m/', verbose_name='Foto')),
                ('tipo', models.CharField(choices=[('ficha_retirada', 'Ficha de Retirada'), ('foto_rainbow', 'Foto da Rainbow'), ('contrato_aluguel', 'Contrato de Aluguel')], max_length=20, verbose_name='Tipo de Foto')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='clientes.cliente', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos_clientes_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Foto do Cliente',
                'verbose_name_plural': 'Fotos dos Clientes',
                'ordering': ['-created_at'],
            },
        ),
    ]
