# Generated by Django 4.2.10 on 2026-01-10 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0005_add_cliente_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_compra_rainbow',
            field=models.DateField(blank=True, help_text='Campo legado - usar relacionamento equipamentos', null=True, verbose_name='Data da Compra Rainbow'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='perfil',
            field=models.CharField(choices=[('diamante', 'Diamante'), ('ouro', 'Ouro'), ('prata', 'Prata'), ('bronze', 'Bronze'), ('pro', 'PRO'), ('lho', 'LHO')], default='lho', max_length=20, verbose_name='Segmentação'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='possui_rainbow',
            field=models.BooleanField(default=False, help_text='Campo legado - usar relacionamento equipamentos', verbose_name='Possui Rainbow'),
        ),
        migrations.CreateModel(
            name='ObservacaoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(help_text='Texto da observação do consultor', verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observacoes_consultor', to='clientes.cliente', verbose_name='Cliente')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observacoes_clientes', to=settings.AUTH_USER_MODEL, verbose_name='Consultor')),
            ],
            options={
                'verbose_name': 'Observação do Cliente',
                'verbose_name_plural': 'Observações dos Clientes',
                'ordering': ['-created_at'],
            },
        ),
    ]
