# Generated by Django 4.2.10 on 2026-01-10 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_add_observacao_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='relatorio',
        ),
    ]
