# Generated by Django 4.2.10 on 2026-01-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_remove_observacoes_relatorio_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='periodicidade_liquido',
            field=models.IntegerField(blank=True, choices=[(3, '3 meses'), (4, '4 meses'), (6, '6 meses'), (8, '8 meses'), (12, '12 meses')], help_text='Período entre compras de líquidos (em meses)', null=True, verbose_name='Periodicidade Líquido'),
        ),
    ]
