# Generated by Django 4.2.10 on 2026-01-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_add_periodicidade_liquido'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='observacao_geral',
            field=models.TextField(blank=True, help_text='Observação geral sobre o cliente (visível para todos)', null=True, verbose_name='Observação Geral'),
        ),
    ]
