# Generated by Django 4.2.10 on 2025-12-14 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(db_index=True, max_length=20, verbose_name='Telefone')),
                ('nome_contato', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do Contato')),
                ('wa_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='WhatsApp ID')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('aguardando', 'Aguardando Resposta'), ('encerrada', 'Encerrada')], default='ativa', max_length=20, verbose_name='Status')),
                ('modo_atendimento', models.CharField(choices=[('ia', 'Atendimento IA'), ('humano', 'Atendimento Humano'), ('hibrido', 'Híbrido')], default='ia', max_length=10, verbose_name='Modo de Atendimento')),
                ('ultima_mensagem_cliente', models.DateTimeField(blank=True, help_text='Para controle da janela de 24h', null=True, verbose_name='Última Msg do Cliente')),
                ('janela_ativa', models.BooleanField(default=False, verbose_name='Janela 24h Ativa')),
                ('contexto_ia', models.JSONField(blank=True, default=dict, help_text='Histórico/contexto para a IA', verbose_name='Contexto IA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atendente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversas_atendidas', to=settings.AUTH_USER_MODEL, verbose_name='Atendente')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversas_whatsapp', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Conversa WhatsApp',
                'verbose_name_plural': 'Conversas WhatsApp',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Template')),
                ('categoria', models.CharField(choices=[('UTILITY', 'Utility (R$0.04)'), ('MARKETING', 'Marketing (R$0.38)'), ('AUTHENTICATION', 'Authentication')], max_length=20, verbose_name='Categoria')),
                ('idioma', models.CharField(default='pt_BR', max_length=10, verbose_name='Idioma')),
                ('status', models.CharField(choices=[('APPROVED', 'Aprovado'), ('PENDING', 'Pendente'), ('REJECTED', 'Rejeitado')], default='PENDING', max_length=20, verbose_name='Status')),
                ('header_text', models.CharField(blank=True, max_length=60, null=True, verbose_name='Header (texto)')),
                ('body_text', models.TextField(help_text='Use {{1}}, {{2}} para variáveis', verbose_name='Body (texto)')),
                ('footer_text', models.CharField(blank=True, max_length=60, null=True, verbose_name='Footer (texto)')),
                ('botoes', models.JSONField(blank=True, default=list, help_text='Lista de botões do template', verbose_name='Botões')),
                ('variaveis', models.JSONField(blank=True, default=list, help_text='Lista de variáveis esperadas', verbose_name='Variáveis')),
                ('descricao_uso', models.TextField(blank=True, help_text='Quando usar este template', null=True, verbose_name='Descrição de Uso')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template de Mensagem',
                'verbose_name_plural': 'Templates de Mensagem',
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wamid', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='WhatsApp Message ID')),
                ('tipo', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('audio', 'Áudio'), ('video', 'Vídeo'), ('document', 'Documento'), ('location', 'Localização'), ('contacts', 'Contato'), ('template', 'Template'), ('interactive', 'Interativo')], default='text', max_length=20, verbose_name='Tipo')),
                ('direcao', models.CharField(choices=[('entrada', 'Recebida'), ('saida', 'Enviada')], max_length=10, verbose_name='Direção')),
                ('status', models.CharField(choices=[('enviando', 'Enviando'), ('enviada', 'Enviada'), ('entregue', 'Entregue'), ('lida', 'Lida'), ('falha', 'Falha')], default='enviando', max_length=20, verbose_name='Status')),
                ('conteudo', models.TextField(help_text='Texto da mensagem ou URL da mídia', verbose_name='Conteúdo')),
                ('media_url', models.URLField(blank=True, null=True, verbose_name='URL da Mídia')),
                ('media_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Media ID WhatsApp')),
                ('mime_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='MIME Type')),
                ('enviado_por_ia', models.BooleanField(default=False, verbose_name='Enviado por IA')),
                ('data_envio', models.DateTimeField(blank=True, null=True, verbose_name='Data de Envio')),
                ('data_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Data de Entrega')),
                ('data_leitura', models.DateTimeField(blank=True, null=True, verbose_name='Data de Leitura')),
                ('erro_mensagem', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='whatsapp_integration.conversa', verbose_name='Conversa')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsapp_integration.template', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampanhaMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Campanha')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('agendada', 'Agendada'), ('enviando', 'Enviando'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='rascunho', max_length=20, verbose_name='Status')),
                ('data_agendada', models.DateTimeField(blank=True, null=True, verbose_name='Data Agendada')),
                ('data_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Data de Início')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('filtro_perfil', models.JSONField(blank=True, default=list, help_text='Ex: ["diamante", "ouro"]', verbose_name='Filtro por Perfil')),
                ('filtro_segmento', models.JSONField(blank=True, default=list, verbose_name='Filtro por Segmento')),
                ('total_destinatarios', models.IntegerField(default=0, verbose_name='Total Destinatários')),
                ('total_enviados', models.IntegerField(default=0, verbose_name='Total Enviados')),
                ('total_entregues', models.IntegerField(default=0, verbose_name='Total Entregues')),
                ('total_lidos', models.IntegerField(default=0, verbose_name='Total Lidos')),
                ('total_falhas', models.IntegerField(default=0, verbose_name='Total Falhas')),
                ('total_respostas', models.IntegerField(default=0, verbose_name='Total Respostas')),
                ('custo_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo Estimado')),
                ('custo_real', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo Real')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanhas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('filtro_consultor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanhas_whatsapp', to=settings.AUTH_USER_MODEL, verbose_name='Filtro por Consultor')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='whatsapp_integration.template', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Campanha de Mensagem',
                'verbose_name_plural': 'Campanhas de Mensagem',
                'ordering': ['-created_at'],
            },
        ),
    ]
